### ISSUE TITLE
安装报错  'git clone' failed with status 128

### ISSUE THREAD

**Issue by qian-kong** [Xutaotaotao/electron-prokit#30]
你好，感觉项目不错来尝试安装下。 
## Environment
 * Node Version: `20.7.0`
 ## Reproduction
 ### Steps to reproduce
1、执行 create electron-prokit myApp
### What is Expected?
安装成功
### What is actually happening?
提示错误 'git clone' failed with status 128
### Additional comments
可以考虑不通过下载模版来创建么？

**Comment by Xutaotaotao** [comment]
可以，这个我优化一下！

**Comment by Xutaotaotao** [comment]
> 你好，感觉项目不错来尝试安装下。
> 
> ## Environment
> * Node Version: `20.7.0`
> 
> ## Reproduction
> ### Steps to reproduce
> 1、执行 create electron-prokit myApp
> 
> ### What is Expected?
> 安装成功
> 
> ### What is actually happening?
> 提示错误 'git clone' failed with status 128
> 
> ### Additional comments
> 可以考虑不通过下载模版来创建么？

**### 已经解决** @qian-kong

**Comment by qian-kong** [comment]
这么快解决啊，小伙上班不是很忙啊！

**Comment by Xutaotaotao** [comment]
> 这么快解决啊，小伙上班不是很忙啊！

就几行代码的事情😂
