### ISSUE TITLE
应用升级方案是否考虑集成到里面

### ISSUE THREAD

**Issue by qian-kong** [Xutaotaotao/electron-prokit#35]
### Additional comments
是否考虑将全量升级和增量升级集成进去，创建项目的时候可以用一个配置项来配置

**Comment by Xutaotaotao** [comment]
这个会做，排期安排上，现在还在疯狂补文档😂

**Comment by Xutaotaotao** [comment]
> ### Additional comments
> 是否考虑将全量升级和增量升级集成进去，创建项目的时候可以用一个配置项来配置

有兴趣一起吗😊

**Comment by qian-kong** [comment]
我先熟悉和学习下源码

**Comment by Xutaotaotao** [comment]
脚手架里面没有，核心库里面有。
