### ISSUE TITLE
源码在windows下运行报错"Failed to load shared library: %1 不是有效的 Win32 应用程序。"

### ISSUE THREAD

**Issue by qian-kong** [Xutaotaotao/electron-prokit#37]
electron-prokit源码本地windows系统下执行`npm run dev`
## Environment
 * Node Version: `20.7.0`
 * OS: Windows 11
 ## Reproduction
 ### Steps to reproduce
1、执行 npm run dev
### What is Expected?
运行成功
### What is actually happening?
提示错误 “Failed to load shared library: %1 不是有效的 Win32 应用程序。”
### Additional comments
`epffi.load(options.path)`出错,是不是koffi不兼容windows

**Comment by qian-kong** [comment]
好的

**Comment by Xutaotaotao** [comment]
已修复
