### ISSUE TITLE
示例代码无法在 arm 架构下运行

### ISSUE THREAD

**Issue by Hiram-Wong** [Xutaotaotao/electron-prokit#40]
<img width="1124" alt="image" src="https://github.com/Xutaotaotao/electron-prokit/assets/30908279/b32456da-c360-43cc-8e19-99ac6f1485df">

**Comment by Xutaotaotao** [comment]
dylib是在x86的电脑上编译的，如果是arm64的话要在arm64电脑上重新编译dlylib

**Comment by Xutaotaotao** [comment]
> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/30908279/278850267-b32456da-c360-43cc-8e19-99ac6f1485df.png">

已修复，编译了满足arm64的dylib，可以再看看，给我反馈一下结果

**Comment by Hiram-Wong** [comment]
程序能正常启，这块调用还有点问题
<img width="963" alt="image" src="https://github.com/Xutaotaotao/electron-prokit/assets/30908279/25cdbe38-11ca-4fee-adb0-bd69f4a14609">

**Comment by Xutaotaotao** [comment]
> 程序能正常启，这块调用还有点问题 <img alt="image" width="963" src="https://user-images.githubusercontent.com/30908279/278922266-25cdbe38-11ca-4fee-adb0-bd69f4a14609.png">

这个是怎么出现的？启动项目后直接跳转到这个页面了？还是点击了什么按钮出现的？

**Comment by Hiram-Wong** [comment]
点击外语言调用

**Comment by Xutaotaotao** [comment]
> 点击外语言调用

点击其他菜单没有问题？就跨语言调用会出现这个界面吗？控制台是否有其他报错呢？

**Comment by Hiram-Wong** [comment]
> > 点击外语言调用
> 
> 点击其他菜单没有问题？就跨语言调用会出现这个界面吗？控制台是否有其他报错呢？

<img width="546" alt="image" src="https://github.com/Xutaotaotao/electron-prokit/assets/30908279/289d6a56-58e7-49ab-bb4f-e0bbf0733edf">

**Comment by Xutaotaotao** [comment]
> > > 点击外语言调用
> > 
> > 
> > 点击其他菜单没有问题？就跨语言调用会出现这个界面吗？控制台是否有其他报错呢？
> 
> <img alt="image" width="546" src="https://user-images.githubusercontent.com/30908279/278923855-289d6a56-58e7-49ab-bb4f-e0bbf0733edf.png">

#41 

联系一下我，帮你具体看看

**Comment by Xutaotaotao** [comment]
> > > 点击外语言调用
> > 
> > 
> > 点击其他菜单没有问题？就跨语言调用会出现这个界面吗？控制台是否有其他报错呢？
> 
> <img alt="image" width="546" src="https://user-images.githubusercontent.com/30908279/278923855-289d6a56-58e7-49ab-bb4f-e0bbf0733edf.png">

现在再pull看下，应该是路由的问题，我换了一种路由模式

**Comment by Xutaotaotao** [comment]
已解决
