### ISSUE TITLE
怎么 build 应用

### ISSUE THREAD

**Issue by Hiram-Wong** [Xutaotaotao/electron-prokit#42]
看了这个示例，只是 打包了src 下的 ejs，并没有打包成 electron 应用[ep-vite-vue3-electron-template](https://github.com/Xutaotaotao/ep-vite-vue3-electron-template)
doc文档也不完整

**Comment by Xutaotaotao** [comment]
yarn run compile

**Comment by Xutaotaotao** [comment]
https://github.com/Xutaotaotao/ep-vite-vue3-electron-template#readme

**Comment by Hiram-Wong** [comment]
> https://github.com/Xutaotaotao/ep-vite-vue3-electron-template#readme

示例compile出来的应用打不开

**Comment by Xutaotaotao** [comment]
报什么错误

**Comment by Hiram-Wong** [comment]
> 报什么错误

直接应用都打不开，dock 栏都没弹

**Comment by Xutaotaotao** [comment]
m系列电脑吗

**Comment by Hiram-Wong** [comment]
> m系列电脑吗

是的，dev 是可以跑起来的

**Comment by Xutaotaotao** [comment]
compile 有没有什么报错

**Comment by Hiram-Wong** [comment]
> compile 有没有什么报错

没有报错

**Comment by Xutaotaotao** [comment]
这个我要看一下，好了告诉你

**Comment by Xutaotaotao** [comment]
可以说下你的操作步骤吗？
是这样的吗
```
npm create electron-prokit myapp
```
然后选择vue 框架
然后安装依赖
然后
```
npm run build
```
然后
```
npm run compile
```

???

**Comment by Hiram-Wong** [comment]
> https://github.com/Xutaotaotao/ep-vite-vue3-electron-template#readme

git clone https://github.com/Xutaotaotao/ep-vite-vue3-electron-template
修改 package.json 模板字符串
yarn 
yarn compile

**Comment by Xutaotaotao** [comment]
你没有yarn build ？？
 先 yarn build 再 yarn compile

**Comment by Xutaotaotao** [comment]
你没有yarn build ？？
 先 yarn build 再 yarn compile

**Comment by Xutaotaotao** [comment]
你没有yarn build ？？
 先 yarn build 再 yarn compile
 
 怪我文档没写好
