### ISSUE TITLE
createWindow-> webPreferences     设置nodeIntegration:true   报 __dirname is not defined

### ISSUE THREAD

**Issue by boyGdm** [Xutaotaotao/electron-prokit#51]
![image](https://github.com/Xutaotaotao/electron-prokit/assets/28535569/884b25d7-94ab-4f90-9552-465dd8e1acbd)

**Comment by Xutaotaotao** [comment]
https://xutaotaotao.github.io/electron-prokit/zh/guide/#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
