### ISSUE TITLE
请问如何在mac下打包win exe程序

### ISSUE THREAD

**Issue by Marootc** [Xutaotaotao/electron-prokit#52]
我使用的是mac系统
在打包的时候只输出了 dmg以及mac.zip 
但并没有输出exe应用程序，请问如何解决这个问题呢？

**Comment by Xutaotaotao** [comment]
mac 下只能打包 mac的包啊，打windows程序需要在windows上打包啊

**Comment by Marootc** [comment]
@Xutaotaotao 好的，谢谢你，这是一个非常棒的项目。
