### ISSUE TITLE
在mac打包后出现空白

### ISSUE THREAD

**Issue by Marootc** [Xutaotaotao/electron-prokit#54]
Debugger listening on ws://127.0.0.1:51715/60570d9b-7472-4b8e-b67b-3d923283a92d
For help, see: https://nodejs.org/en/docs/inspector 

DevTools listening on ws://127.0.0.1:51716/devtools/browser/7f721acf-d8ae-442f-830f-5ee51a2982cf
Error: ENOTDIR: not a directory, stat '/Applications/ElectronProkit.app/Contents/Resources/app.asar/dist/main/node_modules/lowdb'
    at statSync (node:fs:1615:3)
    at tryStatSync (node:internal/modules/esm/resolve:176:13)
    at packageResolve (node:internal/modules/esm/resolve:864:18)
    at moduleResolve (node:internal/modules/esm/resolve:944:20)
    at defaultResolve (node:internal/modules/esm/resolve:1159:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1195:29) {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Applications/ElectronProkit.app/Contents/Resources/app.asar/dist/main/node_modules/lowdb'
}
(node:11605) electron: Failed to load URL: http://localhost:5173/ with error: ERR_CONNECTION_REFUSED
(Use `ElectronProkit --trace-warnings ...` to show where the warning was created) 
这是用Debugger显示的错误代码，打包后的程序在mac下直接空白 控制台没有任何报错

**Comment by Marootc** [comment]
@Xutaotaotao dev模式下没问题能直接启动 ，但是一打包就不行。并且我也yarn build了

**Comment by Marootc** [comment]
![WX20240608-230630](https://github.com/Xutaotaotao/electron-prokit/assets/24379740/0fa1956c-a2c4-495a-9fb4-bbffed6521cc)
![WX20240608-230645](https://github.com/Xutaotaotao/electron-prokit/assets/24379740/2f176895-82d9-4013-a197-22a4507558dc)

**Comment by Xutaotaotao** [comment]
lowdb 是否放在 忽略打包项里面

**Comment by Marootc** [comment]
@Xutaotaotao 
`import type { Configuration } from "electron-builder";

const config: Configuration = {
  productName: "ElectronProkit", // 应用程序名称
  appId: "electron.prokit.com", // 应用程序唯一标识
  copyright: "Copyright © 2023",
  asar: false, // 是否将应用程序打包为asar文件
  files: ["dist/**", "package.json"], // 将要打包的文件或目录
  directories: {
    output: "release", // 打包输出目录
    buildResources: "resources", // 构建资源目录
  },
  extraResources: 
    {
      from: "resources", // 现有的额外静态资源目录
      to: "resources",  // 目标目录，与源目录同名
    },
 
  
  mac: {
    hardenedRuntime: true, // 是否启用硬化运行时
    gatekeeperAssess: false, // 是否允许运行未签名的应用程序
    target: ["dmg", "zip"], // 打包的目标类型
    entitlements: "./scripts/entitlements.mac.plist", // macOS 应用程序权限配置文件的路径
    entitlementsInherit: "./scripts/entitlements.mac.plist", // 操作系统将继承的权限配置文件的路径
    identity: "", // 应用程序签名的证书 ID
    icon: "./resources/icon/icon.icns", // 应用程序图标
    extendInfo: {
      // 额外的 macOS 应用程序属性
      LSUIElement: true, // 启用macOS的无界面模式
      SUFeedURL: "", // 升级检查的 URL
      SUPublicEDKey: "", // 允许升级的公钥
    },
  },
  dmg: {
    backgroundColor: "#ffffff", // 创建 dmg 文件时窗口的背景颜色
    window: { width: 540, height: 380 }, // 创建 dmg 文件时窗口大小
    icon: "./resources/icon/icon.icns", // dmg 文件所带的图标
    iconSize: 128, // 图标大小
    contents: [
      { x: 410, y: 190, type: "link", path: "/Applications" }, // dmg 文件中的可执行文件路径
      { x: 130, y: 190, type: "file" }, // dmg 文件中的文件路径
    ],
    title: "工坊", // dmg 文件的标题
  },
  win: {
    icon: "./resources/icon/icon.ico", // 可执行文件的图标
    target: "nsis", // 打包的目标类型
    requestedExecutionLevel: "requireAdministrator", // 请求管理员权限时用的系统口令
    verifyUpdateCodeSignature: false, // 是否验证更新时的签名，默认为false
    signingHashAlgorithms: [
      // 当签署时，使用的摘要算法列表，支持 sha256 和 sha1。默认使用 sha256。
      "sha256",
      "sha1",
    ],
    rfc3161TimeStampServer: "", // 向 RFC 3161 时间戳服务器注册时使用的 URL。默认情况下，不占用服务。
    certificateFile: "", // 打包时所用的证书文件路径
    certificatePassword: "", // 打包时所用的证书的密码
  },
  nsis: {
    oneClick: true, // 是否一键安装
    language: "2052", // 安装向导语言
    perMachine: true, // 是否在每台机器上安装，需要管理员权限
    createDesktopShortcut: true, // 是否在桌面上创建快捷方式
    createStartMenuShortcut: true, // 是否在开始菜单上创建快捷方式
    guid: "ElectronProkit", // 安装程序的 GUID
    shortcutName: "ElectronProkit", // 创建快捷方式的名称
    artifactName: "ElectronProkit@${version}.${ext}", // 生成安装文件时的文件名
    include: "./build/install/installer.nsh", //包含其他脚本文件的路径
  },
  publish: {
    provider: 'generic',
    url: "http://172.17.194.13:8090"
  }
};

export default config;`
这是打包配置文件好像并没有问题  我发现一个有趣的事情 就是当我dev后在启动打包后的程序 就能正常的显示页面了，总按觉是创建本地服务器失败。

**Comment by Xutaotaotao** [comment]
可以说一下你的具体步骤吗，我好复现，是直接脚手架创建项目，然后直接build吗

**Comment by Marootc** [comment]
@Xutaotaotao 直接git的main分支
```
git clone https://github.com/Xutaotaotao/electron-prokit.git

pnpm i

pnpm run dev
```

**Comment by Xutaotaotao** [comment]
> @Xutaotaotao
> 
> ```
> pnpm create electron-prokit myapp 
> 
> pnpm install
> 
> pnpm run dev
> 
> pnpm run build
> 
> pnpm run compile。
> ```
> 
> 什么都没有修改直接打包运行程序还是空白。错误依旧是上面Debugger提到的这个错误 ![WX20240617-161910](https://private-user-images.githubusercontent.com/24379740/340231520-b1d700aa-9e78-44f8-a7b2-f178d2e84e40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTMxMjgsIm5iZiI6MTcxODYxMjgyOCwicGF0aCI6Ii8yNDM3OTc0MC8zNDAyMzE1MjAtYjFkNzAwYWEtOWU3OC00NGY4LWE3YjItZjE3OGQyZTg0ZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwY2Q1MDFjMGIzOGExOWMyNGNiMTI0NTQ2NmM4ZjNjOGZlYjFmNTY3MmQ2Mjk2YTYxMTFlOWJmYjFjNTU3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VYHB-7hXwDb5w6vvbqIcUVccXEJV9OQ5rx9Z7BywNCY)

好的，我看看

**Comment by Xutaotaotao** [comment]
> @Xutaotaotao
> 
> ```
> pnpm create electron-prokit myapp 
> 
> pnpm install
> 
> pnpm run dev
> 
> pnpm run build
> 
> pnpm run compile。
> ```
> 
> 什么都没有修改直接打包运行程序还是空白。错误依旧是上面Debugger提到的这个错误 ![WX20240617-161910](https://private-user-images.githubusercontent.com/24379740/340231520-b1d700aa-9e78-44f8-a7b2-f178d2e84e40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTc3NzQsIm5iZiI6MTcxODYxNzQ3NCwicGF0aCI6Ii8yNDM3OTc0MC8zNDAyMzE1MjAtYjFkNzAwYWEtOWU3OC00NGY4LWE3YjItZjE3OGQyZTg0ZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkY2Q5ZDEwZTcxMjI3Yzc4ZGE5ZWYwOTgxNWIzNDI0NDFmNWFjMTlhN2U3YjM1NGY1OGQ0ZDVmZmJhYWZhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xPwe4amcc0hoMp05AqJx5bevIy5_eckiDlGgi--ss34)

额，你用yarn或者npm看看，好像pnpm有问题，估计是包管理机制导致的

**Comment by Xutaotaotao** [comment]
发现问题了，我修改一下，最近一直没时间

**Comment by Marootc** [comment]
@Xutaotaotao  你好请问更新了嘛?应该修改什么地方呢？

**Comment by Xutaotaotao** [comment]
https://github.com/Xutaotaotao/electron-prokit/tree/fix-build/play

看下这个 子项目 ，就是之前的配置我分成了四个配置文件，在config 目录下，然后build脚本改造了一下，还没发布release，之前的打包的确有bug，不好意思给你带来困扰

**Comment by Xutaotaotao** [comment]
已解决，可用最新的脚手架生成项目试试
