### ISSUE TITLE
请问有vue版本的教程嘛？

### ISSUE THREAD

**Issue by 12345ZMTHL** [Xutaotaotao/electron-prokit#9]

**Comment by Xutaotaotao** [comment]
> _No description provided._

很简单，你直接Vite创建项目的时候选择vue的模版就行，就渲染进程不一样，其他都一样，如果需要我可以写个教程，然后再将模版放到脚手架里面。 @12345ZMTHL 

记一个TODO

**Comment by 12345ZMTHL** [comment]
> > _No description provided._
> 
> 很简单，你直接Vite创建项目的时候选择vue的模版就行，就渲染进程不一样，其他都一样，如果需要我可以写个教程，然后再将模版放到脚手架里面。 @12345ZMTHL
> 
> 记一个TODO
好的，谢谢，这就去试下

**Comment by Xutaotaotao** [comment]
https://xutaotaotao.github.io/electron-prokit/zh/tutorials/create-vite-electron-service_vue.html

**Comment by Xutaotaotao** [comment]
https://xutaotaotao.github.io/electron-prokit/zh/tutorials/create-vite-electron-service-vue.html

**Comment by 12345ZMTHL** [comment]
> https://xutaotaotao.github.io/electron-prokit/zh/tutorials/create-vite-electron-service-vue.html

谢谢
